"""Quality report assembly (JSON + Markdown). Every number comes from the run that produced it."""

import json
from collections import Counter, defaultdict
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

from ecommerce_search.catalog.quality import parameters as qp
from ecommerce_search.catalog.quality.findings import CheckOutcome, Finding, Severity
from ecommerce_search.catalog.quality.rules import CHECKS, run_checks
from ecommerce_search.catalog.schemas import CatalogRecord
from ecommerce_search.catalog.taxonomy import TAXONOMY_VERSION, TRANSFORM_VERSION

REPORT_VERSION = 1
SYNTHETIC_NOTICE = (
    "ALL RECORDS IN THIS CATALOG ARE SYNTHETIC. They were generated by a project-authored "
    "deterministic generator and are not real marketplace data. No affiliation with, or data "
    "from, Amazon, Flipkart, any other marketplace or any brand named is implied."
)


@dataclass(frozen=True)
class QualityReport:
    source: str  # "file" or "database"
    dataset: Mapping
    total_records: int
    checks: tuple[dict, ...]
    findings: tuple[Finding, ...]
    statistics: Mapping
    # Database audits record the search-index configuration and counts they audited. File
    # reports have no stored search index, so the section states that it is not applicable.
    search_index: Mapping | None = None

    @property
    def error_count(self) -> int:
        return sum(1 for f in self.findings if f.severity is Severity.ERROR)

    @property
    def warning_count(self) -> int:
        return sum(1 for f in self.findings if f.severity is Severity.WARNING)

    @property
    def info_count(self) -> int:
        return sum(1 for f in self.findings if f.severity is Severity.INFO)

    def to_dict(self) -> dict:
        """Deterministic content (no timestamps)."""
        return {
            "report_version": REPORT_VERSION,
            "synthetic_notice": SYNTHETIC_NOTICE if self.dataset.get("is_synthetic") else None,
            "source": self.source,
            "dataset": dict(self.dataset),
            "versions": {
                "rules_version": qp.RULES_VERSION,
                "taxonomy_version": TAXONOMY_VERSION,
                "transform_version": TRANSFORM_VERSION,
            },
            "summary": {
                "records": self.total_records,
                "empty": self.total_records == 0,
                "errors": self.error_count,
                "warnings": self.warning_count,
                "info": self.info_count,
            },
            "checks": list(self.checks),
            "statistics": dict(self.statistics),
            "search_index": dict(self.search_index)
            if self.search_index is not None
            else {"applicable": False, "reason": SEARCH_INDEX_FILE_REASON},
            "parameters": qp.parameters_as_dict(),
            "findings": [f.to_dict() for f in self.findings],
        }


SEARCH_INDEX_FILE_REASON = (
    "Not applicable for file reports: no stored search index exists; search documents are "
    "audited by database audits only."
)


def _status(severity: Severity, outcome: CheckOutcome) -> str:
    if outcome.evaluated == 0 and not outcome.findings:
        return "not_applicable"
    if any(f.severity is Severity.ERROR for f in outcome.findings):
        return "fail"
    if any(f.severity is Severity.WARNING for f in outcome.findings):
        return "warn"
    if outcome.findings:
        return "info"
    return "pass"


def _statistics(records: Sequence[CatalogRecord]) -> dict:
    by_category = Counter(r.category.value for r in records)
    by_brand: dict[str, Counter] = defaultdict(Counter)
    for r in records:
        by_brand[r.category.value][r.brand] += 1
    return {
        "records_by_category": dict(sorted(by_category.items())),
        "records_by_category_and_brand": {
            c: dict(sorted(b.items())) for c, b in sorted(by_brand.items())
        },
    }


def build_report(
    *,
    source: str,
    dataset: Mapping,
    records: Sequence[CatalogRecord],
    total_records: int,
    dataset_synthetic: Mapping[str, bool],
    external: Mapping[str, CheckOutcome],
    search_index: Mapping | None = None,
) -> QualityReport:
    empty = (
        Finding(
            "catalog_non_empty",
            Severity.ERROR,
            "catalog is EMPTY: no records were found. An empty catalog is an error, not a pass "
            "and not 'not applicable'",
        ),
    )
    external = {
        **external,
        "catalog_non_empty": CheckOutcome(1, empty if total_records == 0 else ()),
    }
    outcomes = run_checks(records, dataset_synthetic, external)
    checks, findings = [], []
    for spec in CHECKS:
        outcome = outcomes[spec.name]
        findings.extend(outcome.findings)
        checks.append(
            {
                "name": spec.name,
                "severity_if_failed": spec.severity.value,
                "description": spec.description,
                "status": _status(spec.severity, outcome),
                "evaluated": outcome.evaluated,
                "findings": len(outcome.findings),
                "note": outcome.note,
            }
        )
    return QualityReport(
        source=source,
        dataset=dataset,
        total_records=total_records,
        checks=tuple(checks),
        findings=tuple(sorted(findings, key=Finding.sort_key)),
        statistics=_statistics(records),
        search_index=search_index,
    )


def to_markdown(report: QualityReport, generated_at: str | None = None) -> str:
    d = report.to_dict()
    lines = ["# Catalog quality report", ""]
    if d["synthetic_notice"]:
        lines += [f"> **{d['synthetic_notice']}**", ""]
    ds = d["dataset"]
    lines += [
        f"- Source: {d['source']}",
        f"- Dataset: {ds.get('dataset_id')} version {ds.get('dataset_version')}"
        f" (synthetic: {ds.get('is_synthetic')})",
        f"- Dataset checksum (sha256): {ds.get('checksum_sha256')}",
        f"- Rules / taxonomy / transform versions: {qp.RULES_VERSION} / {TAXONOMY_VERSION}"
        f" / {TRANSFORM_VERSION}",
    ]
    if generated_at:
        lines.append(f"- Generated at: {generated_at}")
    s = d["summary"]
    lines += [
        "",
        f"**Records: {s['records']} | errors: {s['errors']} | warnings: {s['warnings']}"
        f" | info: {s['info']}**",
        "",
        "## Checks",
        "",
        "| Check | If it fails | Status | Evaluated | Findings |",
        "|---|---|---|---|---|",
    ]
    for c in d["checks"]:
        lines.append(
            f"| {c['name']} | {c['severity_if_failed']} | {c['status']} | {c['evaluated']}"
            f" | {c['findings']} |"
        )
    notes = [c for c in d["checks"] if c["note"]]
    if notes:
        lines += ["", "Notes:", ""] + [f"- `{c['name']}`: {c['note']}" for c in notes]
    lines += ["", "## Search index", ""]
    for key, value in d["search_index"].items():
        lines.append(f"- {key}: {value}")
    lines += ["", "## Statistics", "", "```json", json.dumps(d["statistics"], indent=2), "```"]
    lines += [
        "",
        "## Parameters (provisional engineering guardrails, not measured marketplace facts)",
        "",
        "```json",
        json.dumps(d["parameters"], indent=2, ensure_ascii=False),
        "```",
        "",
        "## Findings",
        "",
    ]
    if not d["findings"]:
        lines.append("No findings.")
    for f in d["findings"]:
        where = f["product_id"] or (f"line {f['line']}" if f["line"] else "catalog")
        lines.append(f"- **{f['severity']}** `{f['check']}` [{where}] {f['message']}")
    return "\n".join(lines) + "\n"


def write_report(report: QualityReport, output_dir: Path, stem: str) -> tuple[Path, Path]:
    """Write `<stem>.json` and `<stem>.md`. The only timestamp is added here, not in the data."""
    output_dir.mkdir(parents=True, exist_ok=True)
    generated_at = datetime.now(UTC).isoformat(timespec="seconds")
    payload = {**report.to_dict(), "run": {"generated_at": generated_at}}
    json_path, md_path = output_dir / f"{stem}.json", output_dir / f"{stem}.md"
    json_path.write_text(
        json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    md_path.write_text(to_markdown(report, generated_at), encoding="utf-8")
    return json_path, md_path
