"""create product embeddings

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-01

Creates the Milestone 4 dense-embedding table (pgvector `vector(384)`, ADR-006). The DDL is
written out literally (no application imports). The upgrade creates structure only: vectors are
generated by the application (`python -m ecommerce_search.search embed --database NAME`).
No vector index is created: at 240 rows an exact scan is used (ADR-006); an approximate index
would have to be justified by EXPLAIN evidence first. The pgvector extension from 0001 is not
touched.

Downgrade drops the derived embedding table (it holds no source data; `embed` regenerates it).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import VECTOR

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SHA256 = "~ '^[0-9a-f]{64}$'"


def upgrade() -> None:
    op.create_table(
        "product_embeddings",
        sa.Column("product_id", sa.Text(), nullable=False),
        sa.Column("embedding", VECTOR(384), nullable=False),
        sa.Column("model_id", sa.Text(), nullable=False),
        sa.Column("model_revision", sa.Text(), nullable=False),
        sa.Column("dimension", sa.Integer(), nullable=False),
        sa.Column("normalized", sa.Boolean(), nullable=False),
        sa.Column("embedding_text_version", sa.Text(), nullable=False),
        sa.Column("embedding_config_sha256", sa.Text(), nullable=False),
        sa.Column("source_content_sha256", sa.Text(), nullable=False),
        sa.Column("embedding_text_sha256", sa.Text(), nullable=False),
        sa.Column(
            "embedded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.product_id"],
            name="fk_product_embeddings_product_id_products",
        ),
        sa.PrimaryKeyConstraint("product_id", name="pk_product_embeddings"),
        sa.CheckConstraint(
            "btrim(model_id) <> ''", name=op.f("ck_product_embeddings_model_id_not_blank")
        ),
        sa.CheckConstraint(
            "model_revision ~ '^[0-9a-f]{40}$'",
            name=op.f("ck_product_embeddings_model_revision_format"),
        ),
        sa.CheckConstraint("dimension > 0", name=op.f("ck_product_embeddings_dimension_positive")),
        sa.CheckConstraint(
            "vector_dims(embedding) = dimension",
            name=op.f("ck_product_embeddings_dimension_matches_vector"),
        ),
        sa.CheckConstraint(
            "vector_norm(embedding) > 0", name=op.f("ck_product_embeddings_embedding_nonzero")
        ),
        sa.CheckConstraint(
            "NOT normalized OR abs(vector_norm(embedding) - 1) < 0.001",
            name=op.f("ck_product_embeddings_embedding_normalized"),
        ),
        sa.CheckConstraint(
            "btrim(embedding_text_version) <> ''",
            name=op.f("ck_product_embeddings_embedding_text_version_not_blank"),
        ),
        sa.CheckConstraint(
            f"embedding_config_sha256 {SHA256}",
            name=op.f("ck_product_embeddings_embedding_config_sha256_format"),
        ),
        sa.CheckConstraint(
            f"source_content_sha256 {SHA256}",
            name=op.f("ck_product_embeddings_source_content_sha256_format"),
        ),
        sa.CheckConstraint(
            f"embedding_text_sha256 {SHA256}",
            name=op.f("ck_product_embeddings_embedding_text_sha256_format"),
        ),
    )


def downgrade() -> None:
    op.drop_table("product_embeddings")
